# Imports

In [43]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Converting to Pandas DataFrames

In [45]:
gold_belga_press_articles_df = pd.read_csv('../data/raw/gold_belga_press_articles.csv', sep=',', on_bad_lines='skip')
gold_google_trends_daily_df = pd.read_csv('../data/raw/gold_google_trends_daily.csv', sep=',', on_bad_lines='skip')
gold_match_context_df = pd.read_csv('../data/raw/gold_match_context.csv', sep=',', on_bad_lines='skip')
gold_match_df = pd.read_csv('../data/raw/gold_match.csv', sep=',', on_bad_lines='skip')
gold_match_goals_df = pd.read_csv('../data/raw/gold_match_goals.csv', sep=',', on_bad_lines='skip')
gold_match_tickets_df = pd.read_csv('../data/raw/gold_match_tickets.csv', sep=',', on_bad_lines='skip')

In [46]:
gold_belga_press_articles_df.head()

,article_id,date,title,lead,source,type,match_id,days_to_match
0,16759,2023-01-05,Al 10 eersteklassers in buitenlandse handen en...,che stem hebben.Hoofdaandeelhouder: Randy Fran...,Het Laatste Nieuws,NEWS,NaN,NaN
1,16760,2023-01-05,Football Talk. Ravych (Cercle Brugge) valt voo...,...edwensen van kinderen vervuld worden. Daarn...,Het Laatste Nieuws,NEWS,NaN,NaN
2,16761,2023-01-05,Football Talk. Vandaag nog geen debuut voor Ro...,...edwensen van kinderen vervuld worden. Daarn...,Het Laatste Nieuws,NEWS,NaN,NaN
3,16762,2023-01-05,Jonas Bogaerts en KVK Tienen willen goede reek...,de overwinning tegen OHL betekende ook de eers...,Het Laatste Nieuws,NEWS,NaN,NaN
4,16763,2023-01-05,Mathieu Maertens (OHL): “Sportieve revanche te...,OHL ontvangt zondagavond Kortrijk aan Den Dree...,Het Laatste Nieuws,NEWS,NaN,NaN

In [47]:
gold_google_trends_daily_df.head()

         date  ohl_interest match_id
0  2022-07-01          2.43      NaN
1  2022-07-02          4.25      NaN
2  2022-07-03          4.56      NaN
3  2022-07-04          3.04      NaN
4  2022-07-05          3.65      NaN

In [48]:
gold_match_context_df.head()

,match_id,match_date,weather_temp_max_c,weather_temp_min_c,weather_temp_mean_c,weather_precipitation_mm,weather_rain_mm,weather_snowfall_cm,weather_windspeed_max_kmh,weather_sunshine_hours,...,is_weekend,is_midweek,academic_year,academic_week,is_public_holiday,public_holiday_name,is_school_holiday_flanders,school_holiday_name,pct_free_tickets,campaign_motto
0,d0te6swsv2y99ywgugc2utbmc,2022-07-23,24.7,12.9,19.8,0.1,0.1,0.0,6.9,15.0,...,True,False,2021/2022,47,False,NaN,True,Summer Holiday,0.0,NaN
1,d256yo3eng04m0fu7b4sl7wno,2022-07-30,25.8,12.9,19.8,0.0,0.0,0.0,10.2,10.3,...,True,False,2021/2022,48,False,NaN,True,Summer Holiday,13.9,NaN
2,d3pqkck2grzx98jg4sofhp8us,2022-08-07,24.4,10.8,18.1,0.0,0.0,0.0,14.5,14.2,...,True,False,2021/2022,49,False,NaN,True,Summer Holiday,0.0,NaN
3,d4mn5ksbxuvnaww4pmommxhqs,2022-08-14,32.2,17.3,25.4,0.0,0.0,0.0,16.9,11.1,...,True,False,2021/2022,50,False,NaN,True,Summer Holiday,8.3,NaN
4,d5htdqmc8w72upys41sfxhfkk,2022-08-21,23.4,13.3,18.7,0.0,0.0,0.0,13.4,11.5,...,True,False,2021/2022,51,False,NaN,True,Summer Holiday,0.0,NaN

In [49]:
gold_match_df.head()

,match_id,match_date,kickoff_time_local,match_date_utc,kickoff_time_utc,matchday,competition_id,competition_name,season,season_id,...,venue,winner,result_home,goals_home_ht,goals_away_ht,goals_home_ft,goals_away_ft,is_home_match,last_result_vs_opponent,tickets_scanned
0,d0te6swsv2y99ywgugc2utbmc,2022-07-23,18:15:00,2022-07-23Z,16:15:00Z,1.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,Guldensporenstadion,away,L,0,0,0,2,False,L 1-2,NaN
1,d256yo3eng04m0fu7b4sl7wno,2022-07-30,18:15:00,2022-07-30Z,16:15:00Z,2.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,King Power at Den Dreef Stadion,home,W,1,0,2,0,True,NaN,5565.0
2,d3pqkck2grzx98jg4sofhp8us,2022-08-07,21:00:00,2022-08-07Z,19:00:00Z,3.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,Bosuilstadion,home,W,2,1,4,2,False,L 0-1,NaN
3,d4mn5ksbxuvnaww4pmommxhqs,2022-08-14,18:30:00,2022-08-14Z,16:30:00Z,4.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,King Power at Den Dreef Stadion,away,L,0,2,0,3,True,L 1-4,7440.0
4,d5htdqmc8w72upys41sfxhfkk,2022-08-21,18:30:00,2022-08-21Z,16:30:00Z,5.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,Stade Maurice Dufrasne,away,L,0,2,1,3,False,W 2-1,NaN

In [50]:
gold_match_goals_df.head()

,match_id,match_date,kickoff_time_local,season,stage,competition_name,opponent,period_id,time_min,time_min_sec,is_ohl_goal,scorer_name,assist_player_name,goal_type,home_score_after,away_score_after,var_reviewed,opta_event_id
0,d0te6swsv2y99ywgugc2utbmc,2022-07-23,18:15:00,2022/2023,Regular Season,Belgian Jupiler Pro League,Kortrijk,2,72,71:57,True,M. Maertens,L. Patris,Regular,0,1,NaN,2438482395
1,d0te6swsv2y99ywgugc2utbmc,2022-07-23,18:15:00,2022/2023,Regular Season,Belgian Jupiler Pro League,Kortrijk,2,93,92:03,True,Mousa Tamari,L. Patris,Regular,0,2,NaN,2438491703
2,d256yo3eng04m0fu7b4sl7wno,2022-07-30,18:15:00,2022/2023,Regular Season,Belgian Jupiler Pro League,Westerlo,1,13,12:35,True,J. Þorsteinsson,NaN,Regular,1,0,NaN,2440388221
3,d256yo3eng04m0fu7b4sl7wno,2022-07-30,18:15:00,2022/2023,Regular Season,Belgian Jupiler Pro League,Westerlo,2,77,76:10,True,R. Holzhauser,NaN,Penalty,2,0,NaN,2440445759
4,d3pqkck2grzx98jg4sofhp8us,2022-08-07,21:00:00,2022/2023,Regular Season,Belgian Jupiler Pro League,Antwerp,1,27,26:04,True,N. Nsingi,L. Patris,Regular,0,1,NaN,2443561741

In [51]:
gold_match_tickets_df.head()

,match_id,tickets_sold_b2c,tickets_sold_b2b,tickets_sold_total,seasonpass_holders,tickets_trib1,tickets_trib2_thuis,tickets_trib2_uit,tickets_trib3,tickets_trib4
0,3kewmr690bhoid47mku9wfgno,1095,882,5988,4405,2088,427,1,1903,1569
1,3nrkjdhpc5zse1sdzt1onor2s,1807,953,6652,4405,2256,517,1,2307,1571
2,3rwouz4640n6ngfbwrwsqkp3o,2793,880,7385,4405,2405,572,17,2821,1570
3,3vk3btgbt7w7qy9hjp3f2934k,1981,1003,6929,4405,2441,584,0,2334,1570
4,3yp7glzujzj8nc07qp0sd0kr8,1936,925,6901,4405,2329,566,0,2437,1569